MessengerApp/ViewComponents/RoomViewComponent.cs
using MessengerApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MessengerApp.ViewComponents
{
    public class RoomViewComponent : ViewComponent
    {
        private readonly MessengerDbContext _context;

        public RoomViewComponent(MessengerDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var chats = _context.ChatUsers
                .Include(x => x.Chat)
                .Where(x => x.UserId == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value 
                                                            && x.Chat.Type == Models.ChatType.Room)
                .Select(c => c.Chat)
                .ToList();

            return View(chats);
        }
    }
}

MessengerApp/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Komunikator MessengerApp</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>

    <div class="navbar">
        <span class="logo">FISCORD</span>
        <a asp-controller="Home" asp-action="Index">Pokoje</a>
        <a asp-controller="Home" asp-action="Find">Znajdź</a>
        <a asp-controller="Home" asp-action="Private">Prywatny</a>
    </div>
    <div class="main">

        @if (User.Identity.IsAuthenticated)
        {
            <vc:room></vc:room>
        }
        <div class="chat">
            @RenderBody()
        </div>

        <div class="modal" id="create-room-module">
            <form asp-controller="Home" asp-action="CreateRoom" class="modal-body">
                <button type="button" class="close" onclick="closeModule()">X</button>
                <header>Stwórz pokój</header>
                <div>
                    <input type="text" name="name" />
                </div>
                <footer>
                    <button>Stwórz</button>
                </footer>
            </form>
        </div>

    </div>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>